using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Wega.BloodCult.Ui;

[GenerateTypedNameReferences]
public sealed partial class BloodConstructMenu : RadialMenu
{
    public event Action<string>? OnSelectConstruct;

    public BloodConstructMenu()
    {
        RobustXamlLoader.Load(this);
        InitializeButtons();
    }

    private void InitializeButtons()
    {
        BloodJuggernautButton.OnButtonUp += _ => HandleConstructSelection("MobConstructJuggernaut");
        BloodWraithButton.OnButtonUp += _ => HandleConstructSelection("MobConstructWraith");
        BloodArtificerButton.OnButtonUp += _ => HandleConstructSelection("MobConstructArtificer");
        BloodProteonButton.OnButtonUp += _ => HandleConstructSelection("MobConstructProteon");
		BloodIdolButton.OnButtonUp += _ => HandleConstructSelection("MobConstructIdol");
    }

    private void HandleConstructSelection(string constructName)
    {
        OnSelectConstruct?.Invoke(constructName);
        Close();
    }
}
